### ISSUE TITLE
Requires old version of libglew

### ISSUE THREAD

**Issue by flokargl** [Nocte-/hexahedra#26]
Requires an old version (1.5) of libglew for OpenCL, which is not available per default in older linux distributions.

**Comment by Nocte-** [comment]
On which Linux distro did you run into this problem?

**Comment by flokargl** [comment]
I'm running Debian testing (+stable, unstable and experimental repos). Stable uses libglew1.7, whereas libglew1.5 is only available in the oldstable repo. 
This wouldn't really be a problem in itself as hexahedra runs fine with libglew1.7(when I tested it at least), but it requires /usr/lib/x86_64-linux-gnu/libGLEW.so.<b>1.5</b>
That file isn't available though when version 1.5 isn't installed.

These are the files that exist with version 1.7 installed:
<i>libGLEW.so</i> (_link to libGLEW.so.1.7)
<i>libGLEW.so.1.7</i> (_link to libGLEW.so.1.7.0)
<i>libGLEW.so.1.7.0</i>

I worked around this by creating a link from <i>libGLEW.so.1.5</i> to <i>libGLEW.so</i>, which worked fine. 

Not sure if Ubuntu would run into the same problem, since libglew1.5 is only available in the LTS versions (10.04 and 12.04)

http://packages.debian.org/search?keywords=libglew&searchon=names&suite=all&section=all
http://packages.ubuntu.com/search?keywords=glew

**Comment by Nocte-** [comment]
I tried to reproduce it with Debian testing, but it seems to link everything fine against libglew 1.7. Do you have an idea which component introduced the dependency on 1.5? Did you build SFML2, Rhea, and ES from source?

**Comment by flokargl** [comment]
Alright, this is an error on my part. Looks like I derped the SFML install. I rebuilt everything from scratch and it works fine now. Sorry for the inconvenience.
