### ISSUE TITLE
Build fails. OpenCL Dependency?

### ISSUE THREAD

**Issue by friederschueler** [Nocte-/hexahedra#36]
I am very interested in this project and I am very happy that you are still working on this, but sadly I can not build it on my machine (Archlinux x86_64). I tried to install libcl, but it failed. Same for Travis build it seems: https://travis-ci.org/Nocte-/hexahedra/builds

I installed an OpenCL implementation now and now it builds, but USE_OPENCL is "OFF". It seems that there is a dependendy to OpenCl wheter you use it or not.

Now (after some other minor issues) my build fails with:

[ 73%] Building CXX object hexa/server/CMakeFiles/hexahedra-server.dir/main.cpp.o
/home/frieder/Workspace/hexahedra/hexa/server/main.cpp: In Funktion »int main(int, char*_)«:
/home/frieder/Workspace/hexahedra/hexa/server/main.cpp:321:17: Fehler: »class hexa::noise::generator_context« hat kein Element namens »set_global«
         gen_ctx.set_global("seed", 2.0);
                 ^
hexa/server/CMakeFiles/hexahedra-server.dir/build.make:57: recipe for target 'hexa/server/CMakeFiles/hexahedra-server.dir/main.cpp.o' failed
make[2]: *_\* [hexa/server/CMakeFiles/hexahedra-server.dir/main.cpp.o] Error 1
CMakeFiles/Makefile2:321: recipe for target 'hexa/server/CMakeFiles/hexahedra-server.dir/all' failed
make[1]: **\* [hexa/server/CMakeFiles/hexahedra-server.dir/all] Error 2
Makefile:126: recipe for target 'all' failed
make: **\* [all] Error 2

**Comment by Nocte-** [comment]
Hi there, thanks for the bug report! I've just pushed a fix to the issue35 branch. Just a heads up: the issue35 branch has all the neat HNDL terrain generation stuff, but it's messy to set up, some of the Lua API doesn't work, and you can't log in to the multiplayer server (slight protocol differences). The master branch should work out of the box and connect to the server just fine.

I'll see if I can get the branch in a somewhat usable state today, so you can check it out. :)
