### ISSUE TITLE
Relatives paths possible? CMake config?

### ISSUE THREAD

**Issue by friederschueler** [Nocte-/hexahedra#39]
This is a feature request: I think it would be nice, to have a option to just store all files and libs etc. needed for the game relative to the binary if you compile it with static linking. So you can just copy the whole directory with all the files to another pc and run the game. I know that is not the old school linux way, but better for a game. You can provide a zip file and players only unzip and run it.
Maybe this is already possible, but I need more time to investigate the CMake config and the sources.

**Comment by friederschueler** [comment]
Can be closed, I used static compile option and pointed all the directories to the same folder.

**Comment by Nocte-** [comment]
That's a really good idea for the Windows build. It stores everything in %appdata% but that's easy to fix.
